"use client";
import Image from "next/image";import {ArrowRight,ArrowUpRight,MapPin,Phone} from "lucide-react";import {Reveal,Label} from "./Reveal";import {events} from "@/data/events";import {gallery} from "@/data/gallery";import {site} from "@/data/site";
const experiences=[{n:"01",title:"Good Food",text:"Familiar favourites. Bold flavours. Zero boring plates.",image:"/images/food/kitchen.png"},{n:"02",title:"Better Pours",text:"Cold, crafted and made for conversations that run late.",image:"/images/drinks/pour.png"},{n:"03",title:"Good Times",text:"Music, people, energy — the kind of evening you don't rush.",image:"/images/social/friends.png"}];
export default function Sections(){return <>
 <section id="story" className="statement light"><div className="statement-index">01 — 11</div><Reveal><Label>This is Dicey&apos;s</Label><h2>Come for the food.<br/><em>Stay for everything else.</em></h2></Reveal><div className="statement-foot"><Reveal><p>Dicey&apos;s is where comfort food, crafted pours, music and conversations come together under one roof.</p></Reveal><Reveal delay={.1} className="statement-image"><Image src="/images/social/friends.png" alt="Friends gathered around a table" fill sizes="(max-width: 768px) 80vw, 34vw"/></Reveal></div></section>
 <section id="experience" className="experience dark"><Reveal><Label>The Dicey&apos;s Experience</Label><h2>Eat. Pour.<br/>Play. <em>Repeat.</em></h2></Reveal><div className="experience-grid">{experiences.map((x,i)=><Reveal key={x.title} delay={i*.08} className={`experience-panel panel-${i+1}`}><div className="panel-image"><Image src={x.image} alt={x.title} fill sizes="(max-width: 768px) 100vw, 40vw"/></div><div className="panel-copy"><span>{x.n}</span><h3>{x.title}</h3><p>{x.text}</p></div></Reveal>)}</div></section>
 <section id="food" className="feature food dark"><div className="backword">KITCHEN</div><Reveal className="feature-copy"><Label>01 / Kitchen</Label><h2>Serious<br/>about<br/><em>food.</em></h2><p>Comfort classics, bar favourites and dishes designed to keep the table ordering one more round.</p><a className="text-link" href="#gallery">View food <ArrowRight/></a></Reveal><Reveal className="feature-image"><Image src="/images/food/kitchen.png" alt="A charred dish from the Dicey's kitchen" fill sizes="(max-width: 768px) 94vw, 55vw"/></Reveal></section>
 <section id="drinks" className="drinks"><Image className="drinks-bg" src="/images/drinks/pour.png" alt="" fill sizes="100vw"/><div className="drinks-shade"/><Reveal className="drinks-copy"><Label>02 / The Pour</Label><h2>Poured<br/>just<br/><em>right.</em></h2><p>Cold, crafted and measured by the moment — not the clock.</p><a className="button primary" href="#gallery">Explore drinks <ArrowRight size={16}/></a></Reveal></section>
 <div className="marquee" aria-label="Good food, better pours, good times, Dicey's"><div>Good Food ✦ Better Pours ✦ Good Times ✦ Dicey&apos;s ✦ Good Food ✦ Better Pours ✦ Good Times ✦ Dicey&apos;s ✦</div></div>
 <section className="ambience"><Image src="/images/ambience/night.png" alt="Dicey's dining room after dark" fill sizes="100vw"/><div className="ambience-shade"/><Reveal><Label>After dark</Label><h2>When the<br/>lights go down,<br/><em>Dicey&apos;s comes alive.</em></h2><p>Dinner plans have a habit of turning into late nights here.</p></Reveal></section>
 <section id="events" className="events light"><Reveal className="events-head"><Label>On the calendar</Label><h2>What&apos;s<br/>happening<br/><em>at Dicey&apos;s</em></h2><a className="text-link" href="#location">View all events <ArrowRight/></a></Reveal><div className="event-list">{events.map((event,i)=><Reveal className="event-card" delay={i*.08} key={event.title}><div className="event-image"><Image src={event.image} alt={event.title} fill sizes="(max-width: 768px) 90vw, 30vw"/></div><div className="event-meta"><span>{event.day}</span><span>0{i+1}</span></div><h3>{event.title}</h3><p>{event.note}</p></Reveal>)}</div></section>
 <section id="gallery" className="gallery dark"><Reveal><Label>Scenes from Dicey&apos;s</Label><h2>Looks good.<br/><em>Feels better.</em></h2></Reveal><div className="gallery-grid">{gallery.map((item,i)=><Reveal className={`gallery-item ${item.span}`} delay={(i%3)*.06} key={item.src}><Image src={item.src} alt={item.alt} fill sizes="(max-width: 768px) 100vw, 50vw"/></Reveal>)}</div></section>
 <section className="social dark"><div><Label>Follow along</Label><h2>Seen at<br/><em>Dicey&apos;s</em></h2><p>{site.instagram}</p></div><div className="social-strip">{gallery.slice(0,4).map((x,i)=><div key={i}><Image src={x.src} alt="" fill sizes="25vw"/></div>)}</div><a className="text-link light-link" href="https://instagram.com" target="_blank">Follow Dicey&apos;s <ArrowUpRight/></a></section>
 <section id="location" className="location light"><Reveal><Label>Golf Club Road · Bengaluru</Label><h2>Your table&apos;s<br/><em>waiting.</em></h2></Reveal><div className="location-grid"><div><h3>Dicey&apos;s</h3><p>{site.location[0]}<br/>{site.location[1]}</p><div className="location-actions"><a className="button dark-button" href={site.mapsUrl} target="_blank"><MapPin size={16}/> Get directions</a><a className="button line-button" href={`tel:+91${site.phones[0]}`}><Phone size={16}/> Call Dicey&apos;s</a></div></div><div><span className="mini">Opening hours</span><p>{site.hours.days}<br/>{site.hours.time}</p></div><div><span className="mini">Reservations</span>{site.phones.map(p=><a href={`tel:+91${p}`} key={p}>+91 {p}</a>)}</div></div></section>
 </>}
